#pragma once

enum Event
{
  EVENT_NONE = 0,
  EVENT_RESET = 1,
  EVENT_TOGGLE_LED = 2,
  EVENT_INC_DELAY = 4,
  EVENT_DEC_DELAY = 8,
};

#define TASK_TOGGLE_DELAY 50
#define TASK_DELAY_DELAY 50
#define TASK_IDLE_DELAY 200

#define LED_INITIAL_DELAY 500
#define MIN_LED_DELAY 100
#define MAX_LED_DELAY 2000
#define LED_DELAY_STEP 100

#define LED_1_PIN 2
#define LED_2_PIN 3
#define BTN_RST_PIN 4
#define BTN_SWC_PIN 7
#define BTN_DEC_PIN 6
#define BTN_INC_PIN 5
